######################################################################
# Automatically generated by qmake (2.01a) Do. Okt 6 17:32:44 2011
######################################################################

TEMPLATE = app

#QT += xml

TARGET = polylineReplacer

CONFIG = qt warn_on debug

DEPENDPATH += .
INCLUDEPATH += .

HEADERS += resource.h

# Input
SOURCES += polylineReplacer.cpp
