######################################################################
# $Id$
#
# Automatically generated by qmake (2.01a) Do. Okt 6 17:32:44 2011
######################################################################

TEMPLATE = app
TARGET = cityNamesGns

CONFIG = qt warn_on debug

DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += cityNamesGns.cpp
